import type { Category, Listing } from "./types"

export const categories: Category[] = [
  {
    id: "emlak",
    name: "Emlak",
    icon: "🏠",
    count: 1250,
    subcategories: [
      { id: "konut", name: "Konut", count: 450 },
      { id: "isyeri", name: "İşyeri", count: 180 },
      { id: "arsa", name: "Arsa", count: 120 },
      { id: "bina", name: "Bina", count: 85 },
      { id: "turistik", name: "Turistik Tesis", count: 45 },
      { id: "kooperatif", name: "Kooperatif", count: 30 },
      { id: "proje", name: "Projeler", count: 340 },
    ],
  },
  {
    id: "vasita",
    name: "Vasıta",
    icon: "🚗",
    count: 3420,
    subcategories: [
      { id: "otomobil", name: "Otomobil", count: 2100 },
      { id: "arazi", name: "Arazi, SUV & Pickup", count: 450 },
      { id: "motosiklet", name: "Motosiklet", count: 320 },
      { id: "minivan", name: "Minivan & Panelvan", count: 180 },
      { id: "ticari", name: "Ticari Araçlar", count: 220 },
      { id: "tekne", name: "Deniz Araçları", count: 85 },
      { id: "karavan", name: "Karavan", count: 65 },
    ],
  },
  {
    id: "yedek-parca",
    name: "Yedek Parça & Aksesuar",
    icon: "🔧",
    count: 890,
    subcategories: [
      { id: "otomobil-parca", name: "Otomobil Yedek Parça", count: 420 },
      { id: "motor-parca", name: "Motosiklet Yedek Parça", count: 180 },
      { id: "aksesuar", name: "Aksesuar", count: 150 },
      { id: "lastik", name: "Lastik & Jant", count: 90 },
      { id: "navigasyon", name: "Navigasyon & Elektronik", count: 50 },
    ],
  },
  {
    id: "elektronik",
    name: "Elektronik",
    icon: "💻",
    count: 2100,
    subcategories: [
      { id: "telefon", name: "Cep Telefonu", count: 650 },
      { id: "bilgisayar", name: "Bilgisayar", count: 420 },
      { id: "tablet", name: "Tablet", count: 180 },
      { id: "tv", name: "TV & Görüntü", count: 280 },
      { id: "ses", name: "Ses Sistemleri", count: 150 },
      { id: "foto", name: "Fotoğraf & Kamera", count: 220 },
      { id: "oyun", name: "Oyun & Konsol", count: 200 },
    ],
  },
  {
    id: "gaming",
    name: "Gaming Items",
    icon: "🎮",
    count: 2850,
    subcategories: [
      { id: "csgo", name: "CS:GO Items", count: 850 },
      { id: "valorant", name: "Valorant Accounts", count: 420 },
      { id: "fortnite", name: "Fortnite Skins", count: 380 },
      { id: "dota2", name: "Dota 2 Items", count: 320 },
      { id: "lol", name: "League of Legends", count: 280 },
      { id: "pubg", name: "PUBG Items", count: 250 },
      { id: "apex", name: "Apex Legends", count: 180 },
      { id: "rocket", name: "Rocket League", count: 170 },
    ],
  },
  {
    id: "ev-yasam",
    name: "Ev & Yaşam",
    icon: "🛋️",
    count: 1560,
    subcategories: [
      { id: "mobilya", name: "Mobilya", count: 420 },
      { id: "beyaz-esya", name: "Beyaz Eşya", count: 320 },
      { id: "dekorasyon", name: "Dekorasyon", count: 280 },
      { id: "bahce", name: "Bahçe & Yapı Market", count: 220 },
      { id: "mutfak", name: "Mutfak & Sofra", count: 180 },
      { id: "aydınlatma", name: "Aydınlatma", count: 140 },
    ],
  },
  {
    id: "is-makineleri",
    name: "İş Makineleri & Sanayi",
    icon: "🏗️",
    count: 340,
    subcategories: [
      { id: "insaat", name: "İnşaat Makineleri", count: 120 },
      { id: "tarim", name: "Tarım Makineleri", count: 85 },
      { id: "forklift", name: "Forklift", count: 45 },
      { id: "jenerator", name: "Jeneratör", count: 40 },
      { id: "sanayi", name: "Sanayi Ekipmanları", count: 50 },
    ],
  },
  {
    id: "hobi",
    name: "Hobi & Eğlence",
    icon: "🎯",
    count: 780,
    subcategories: [
      { id: "kitap", name: "Kitap & Dergi", count: 220 },
      { id: "muzik", name: "Müzik Aletleri", count: 180 },
      { id: "spor", name: "Spor Ekipmanları", count: 150 },
      { id: "koleksiyon", name: "Koleksiyon", count: 120 },
      { id: "sanat", name: "Sanat & El İşi", count: 110 },
    ],
  },
  {
    id: "giyim",
    name: "Giyim & Aksesuar",
    icon: "👔",
    count: 920,
    subcategories: [
      { id: "erkek", name: "Erkek Giyim", count: 280 },
      { id: "kadin", name: "Kadın Giyim", count: 320 },
      { id: "cocuk", name: "Çocuk Giyim", count: 180 },
      { id: "ayakkabi", name: "Ayakkabı", count: 90 },
      { id: "canta", name: "Çanta", count: 50 },
    ],
  },
  {
    id: "is-ilanlari",
    name: "İş İlanları",
    icon: "💼",
    count: 450,
    subcategories: [
      { id: "yazilim", name: "Yazılım", count: 120 },
      { id: "muhendis", name: "Mühendislik", count: 85 },
      { id: "satis", name: "Satış & Pazarlama", count: 90 },
      { id: "muhasebe", name: "Muhasebe & Finans", count: 70 },
      { id: "egitim", name: "Eğitim", count: 85 },
    ],
  },
  {
    id: "hayvanlar",
    name: "Hayvanlar Alemi",
    icon: "🐕",
    count: 230,
    subcategories: [
      { id: "kopek", name: "Köpek", count: 85 },
      { id: "kedi", name: "Kedi", count: 70 },
      { id: "kus", name: "Kuş", count: 35 },
      { id: "akvaryum", name: "Akvaryum", count: 25 },
      { id: "diger", name: "Diğer", count: 15 },
    ],
  },
]

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Satılık Daire - Kadıköy",
    description: "3+1, 120m², Asansörlü, Merkezi konumda",
    price: 3500000,
    category: "emlak",
    location: "İstanbul, Kadıköy",
    images: ["/modern-apartment.png"],
    userId: "user1",
    userName: "Ahmet Yılmaz",
    userPhone: "0532 123 45 67",
    createdAt: new Date().toISOString(),
    views: 245,
    isFeatured: true,
  },
  {
    id: "2",
    title: "2018 Model Volkswagen Passat",
    description: "Dizel, Otomatik, 85.000 km, Hatasız",
    price: 650000,
    category: "vasita",
    location: "Ankara, Çankaya",
    images: ["/volkswagen-passat.png"],
    userId: "user2",
    userName: "Mehmet Demir",
    userPhone: "0533 234 56 78",
    createdAt: new Date().toISOString(),
    views: 189,
  },
  {
    id: "3",
    title: "iPhone 14 Pro Max 256GB",
    description: "Sıfır ayarında, kutulu, garantili",
    price: 42000,
    category: "elektronik",
    location: "İzmir, Bornova",
    images: ["/iphone-14-pro-max.png"],
    userId: "user3",
    userName: "Ayşe Kaya",
    userPhone: "0534 345 67 89",
    createdAt: new Date().toISOString(),
    views: 312,
    isFeatured: true,
  },
  {
    id: "4",
    title: "Kiralık Villa - Bodrum",
    description: "Deniz manzaralı, havuzlu, 4+1",
    price: 25000,
    category: "emlak",
    location: "Muğla, Bodrum",
    images: ["/luxury-villa-pool.png"],
    userId: "user4",
    userName: "Fatma Şahin",
    userPhone: "0535 456 78 90",
    createdAt: new Date().toISOString(),
    views: 567,
  },
  {
    id: "5",
    title: 'MacBook Pro M2 14"',
    description: "16GB RAM, 512GB SSD, Garantili",
    price: 38000,
    category: "elektronik",
    location: "İstanbul, Beşiktaş",
    images: ["/macbook-pro-laptop.png"],
    userId: "user5",
    userName: "Can Öztürk",
    userPhone: "0536 567 89 01",
    createdAt: new Date().toISOString(),
    views: 423,
  },
  {
    id: "6",
    title: "2020 Model Honda Civic",
    description: "Benzin, Manuel, 45.000 km",
    price: 580000,
    category: "vasita",
    location: "Bursa, Nilüfer",
    images: ["/honda-civic.png"],
    userId: "user6",
    userName: "Zeynep Arslan",
    userPhone: "0537 678 90 12",
    createdAt: new Date().toISOString(),
    views: 198,
  },
  {
    id: "7",
    title: "CS:GO Karambit Fade Factory New",
    description: "100% Fade, 0.008 Float, Perfect Corner",
    price: 12500,
    category: "gaming",
    location: "Global",
    images: ["/csgo-karambit.png"],
    userId: "user7",
    userName: "ProGamer",
    userPhone: "Steam Trade",
    createdAt: new Date().toISOString(),
    views: 892,
    isFeatured: true,
  },
  {
    id: "8",
    title: "Valorant Account - Immortal 3",
    description: "All Agents Unlocked, 50+ Skins, Radiant Ready",
    price: 850,
    category: "gaming",
    location: "EU Server",
    images: ["/valorant-account.png"],
    userId: "user8",
    userName: "ValMaster",
    userPhone: "Discord: ValMaster#1234",
    createdAt: new Date().toISOString(),
    views: 456,
  },
  {
    id: "9",
    title: "Fortnite Rare Skins Bundle",
    description: "Renegade Raider, Ghoul Trooper, Black Knight",
    price: 2200,
    category: "gaming",
    location: "Global",
    images: ["/fortnite-skins.png"],
    userId: "user9",
    userName: "FortnitePro",
    userPhone: "Epic: FortnitePro",
    createdAt: new Date().toISOString(),
    views: 678,
    isFeatured: true,
  },
]

export const games = [
  { id: "csgo", name: "CS:GO", icon: "🔫" },
  { id: "valorant", name: "Valorant", icon: "🎯" },
  { id: "fortnite", name: "Fortnite", icon: "🏗️" },
  { id: "dota2", name: "Dota 2", icon: "⚔️" },
  { id: "pubg", name: "PUBG", icon: "🎮" },
  { id: "lol", name: "League of Legends", icon: "🏆" },
  { id: "apex", name: "Apex Legends", icon: "🎪" },
  { id: "rocket-league", name: "Rocket League", icon: "🚗" },
]

export const rarities = [
  { id: "common", name: "Common", color: "#9CA3AF" },
  { id: "uncommon", name: "Uncommon", color: "#10B981" },
  { id: "rare", name: "Rare", color: "#3B82F6" },
  { id: "epic", name: "Epic", color: "#8B5CF6" },
  { id: "legendary", name: "Legendary", color: "#F59E0B" },
  { id: "mythic", name: "Mythic", color: "#EF4444" },
]
