export const vehicleTypes = [
  { id: "car", name: "Otomobil" },
  { id: "suv", name: "SUV" },
  { id: "motorcycle", name: "Motosiklet" },
  { id: "truck", name: "Kamyonet" },
  { id: "van", name: "Minivan & Panelvan" },
  { id: "commercial", name: "Ticari Araçlar" },
  { id: "bus", name: "Otobüs & Midibüs" },
  { id: "trailer", name: "Karavan" },
  { id: "atv", name: "ATV" },
  { id: "scooter", name: "Scooter" },
]

export const vehicleBrands = [
  {
    id: "audi",
    name: "Audi",
    models: ["A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron"],
  },
  {
    id: "bmw",
    name: "BMW",
    models: [
      "1 Serisi",
      "2 Serisi",
      "3 Serisi",
      "4 Serisi",
      "5 Serisi",
      "6 Serisi",
      "7 Serisi",
      "8 Serisi",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z4",
      "i3",
      "i4",
      "iX",
    ],
  },
  {
    id: "mercedes",
    name: "Mercedes-Benz",
    models: [
      "A Serisi",
      "B Serisi",
      "C Serisi",
      "CLA",
      "CLS",
      "E Serisi",
      "S Serisi",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "G Serisi",
      "AMG GT",
      "EQC",
      "EQS",
    ],
  },
  {
    id: "volkswagen",
    name: "Volkswagen",
    models: [
      "Polo",
      "Golf",
      "Jetta",
      "Passat",
      "Arteon",
      "T-Roc",
      "T-Cross",
      "Tiguan",
      "Touareg",
      "Caddy",
      "Transporter",
      "ID.3",
      "ID.4",
    ],
  },
  {
    id: "toyota",
    name: "Toyota",
    models: [
      "Corolla",
      "Camry",
      "Yaris",
      "Auris",
      "Avensis",
      "C-HR",
      "RAV4",
      "Land Cruiser",
      "Hilux",
      "Proace",
      "Prius",
      "bZ4X",
    ],
  },
  {
    id: "ford",
    name: "Ford",
    models: [
      "Fiesta",
      "Focus",
      "Mondeo",
      "Mustang",
      "EcoSport",
      "Puma",
      "Kuga",
      "Explorer",
      "Ranger",
      "Transit",
      "Transit Custom",
      "Mustang Mach-E",
    ],
  },
  {
    id: "renault",
    name: "Renault",
    models: ["Clio", "Megane", "Talisman", "Captur", "Kadjar", "Koleos", "Kangoo", "Trafic", "Master", "Zoe", "Twingo"],
  },
  {
    id: "peugeot",
    name: "Peugeot",
    models: ["208", "308", "508", "2008", "3008", "5008", "Rifter", "Partner", "Boxer", "e-208", "e-2008"],
  },
  {
    id: "fiat",
    name: "Fiat",
    models: ["500", "Panda", "Tipo", "Egea", "500X", "500L", "Doblo", "Ducato", "Fiorino", "500e"],
  },
  {
    id: "honda",
    name: "Honda",
    models: ["Civic", "Accord", "Jazz", "CR-V", "HR-V", "e", "City"],
  },
  {
    id: "hyundai",
    name: "Hyundai",
    models: [
      "i10",
      "i20",
      "i30",
      "Elantra",
      "Sonata",
      "Bayon",
      "Kona",
      "Tucson",
      "Santa Fe",
      "Ioniq",
      "Ioniq 5",
      "Ioniq 6",
    ],
  },
  {
    id: "kia",
    name: "Kia",
    models: ["Picanto", "Rio", "Ceed", "Stonic", "XCeed", "Sportage", "Sorento", "Niro", "EV6", "EV9"],
  },
  {
    id: "nissan",
    name: "Nissan",
    models: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Navara"],
  },
  {
    id: "opel",
    name: "Opel",
    models: ["Corsa", "Astra", "Insignia", "Crossland", "Grandland", "Mokka", "Combo", "Vivaro", "Movano"],
  },
  {
    id: "skoda",
    name: "Skoda",
    models: ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  },
  {
    id: "seat",
    name: "Seat",
    models: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  },
  {
    id: "mazda",
    name: "Mazda",
    models: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  },
  {
    id: "volvo",
    name: "Volvo",
    models: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40", "EX30", "EX90"],
  },
  {
    id: "tesla",
    name: "Tesla",
    models: ["Model 3", "Model S", "Model X", "Model Y"],
  },
  {
    id: "dacia",
    name: "Dacia",
    models: ["Sandero", "Logan", "Duster", "Jogger", "Spring"],
  },
  {
    id: "citroen",
    name: "Citroën",
    models: ["C3", "C4", "C5 Aircross", "Berlingo", "Jumpy", "e-C4"],
  },
  {
    id: "mitsubishi",
    name: "Mitsubishi",
    models: ["Space Star", "ASX", "Eclipse Cross", "Outlander", "L200"],
  },
  {
    id: "suzuki",
    name: "Suzuki",
    models: ["Swift", "Vitara", "S-Cross", "Jimny", "Ignis"],
  },
  {
    id: "jeep",
    name: "Jeep",
    models: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator"],
  },
  {
    id: "land-rover",
    name: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Evoque",
      "Range Rover Velar",
    ],
  },
  {
    id: "porsche",
    name: "Porsche",
    models: ["911", "718", "Taycan", "Panamera", "Macan", "Cayenne"],
  },
  {
    id: "lexus",
    name: "Lexus",
    models: ["IS", "ES", "LS", "UX", "NX", "RX", "LX"],
  },
  {
    id: "alfa-romeo",
    name: "Alfa Romeo",
    models: ["Giulia", "Stelvio", "Tonale"],
  },
  {
    id: "mini",
    name: "Mini",
    models: ["Cooper", "Countryman", "Clubman", "Electric"],
  },
]

export const engineTypes = [
  { id: "gasoline", name: "Benzin" },
  { id: "diesel", name: "Dizel" },
  { id: "hybrid", name: "Hibrit" },
  { id: "electric", name: "Elektrik" },
  { id: "lpg", name: "LPG & CNG" },
]

export const engineSizes = [
  "1.0",
  "1.2",
  "1.3",
  "1.4",
  "1.5",
  "1.6",
  "1.8",
  "2.0",
  "2.2",
  "2.4",
  "2.5",
  "2.7",
  "3.0",
  "3.2",
  "3.5",
  "3.6",
  "4.0",
  "4.2",
  "4.4",
  "5.0",
  "5.5",
  "6.0",
  "6.2",
]

export const transmissionTypes = [
  { id: "manual", name: "Manuel" },
  { id: "automatic", name: "Otomatik" },
  { id: "semi-automatic", name: "Yarı Otomatik" },
]

export const fuelTypes = engineTypes

export const colors = [
  "Beyaz",
  "Siyah",
  "Gri",
  "Gümüş",
  "Mavi",
  "Kırmızı",
  "Yeşil",
  "Sarı",
  "Turuncu",
  "Kahverengi",
  "Mor",
  "Altın",
  "Bronz",
]

export const years = Array.from({ length: 30 }, (_, i) => (new Date().getFullYear() - i).toString())
